export const versionControlSkill = {
  profileId: 93750,
  level: 5,
  levelGoal: null,
  levelGoalDeadline: null,
  keyword: {
    id: 686,
    type: 6,
    masterSynonymId: 2955,
    masterSynonym: 'Versionshanteringsverktyg',
    synonyms: [
      'Versionshanteringsverktyg',
      'Version control',
      'Version Control System',
    ],
    universal: false,
    verified: true,
  },
  changeHistory: [
    {
      id: 1466907,
      changeDateTime: '2021-01-15T15:16:01.4049619',
      level: 0,
      profileId: 93750,
      keywordId: 686,
      favourite: false,
    },
    {
      id: 1492736,
      changeDateTime: '2021-02-11T09:33:58.4981278',
      level: 5,
      profileId: 93750,
      keywordId: 686,
      favourite: false,
    },
  ],
  translations: [
    {
      keywordId: 686,
      keywordSynonymId: 24587,
      keywordSynonym: {
        keywordId: 686,
        id: 24587,
        keyword: {
          id: 686,
          type: 6,
          masterSynonymId: 2955,
          masterSynonym: 'Versionshanteringsverktyg',
          synonyms: [
            'Versionshanteringsverktyg',
            'Version control',
            'Version Control System',
          ],
          universal: false,
          verified: true,
        },
        name: 'Version control',
        seoId: 'version-control',
        description: 'Version control',
        languageId: 560,
      },
      keyword: {
        id: 686,
        type: 6,
        masterSynonymId: 2955,
        masterSynonym: 'Versionshanteringsverktyg',
        synonyms: [
          'Versionshanteringsverktyg',
          'Version control',
          'Version Control System',
        ],
        universal: false,
        verified: true,
      },
      profileId: 93750,
      profileTranslationId: 112481,
      profileTranslation: {
        profileTranslationId: 112481,
        profileId: 93750,
        languageBranchId: 2,
        languageBranch: {
          id: 2,
          languageId: 560,
          language: {
            languageId: 560,
            name: 'English',
            culture: 'en-GB',
            lang: 'en',
            country: 'GB',
          },
          enabled: true,
        },
      },
    },
  ],
  favourite: false,
  companyId: 1884,
  companyUserId: 75479,
  id: 686,
  url: null,
  links: null,
};
