name: Release
on:
  workflow_run:
    branches: [master]
    workflows: ['Test']
    types: [completed]
jobs:
  # todo
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
