name: Test
on: [push]
env:
  HUSKY: '0'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Check out repository code
        uses: actions/checkout@v2

      - run: npm install
      - run: npm run full
