name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Check out repository code
        uses: actions/checkout@v2

      - run: npm install
      - run: echo -e "CINODE_COMPANY_ID=1234\nCINODE_COMPANY_NAME=foobarbaz\nCINODE_ACCESS_ID=foo\nCINODE_ACCESS_SECRET=bar" > .env
      - run: npm run full
